<a href="https://colab.research.google.com/github/intraprasart/Quantum-Perceptron-Machine-Learning-using-Nitch-Fitness-Operator/blob/Thorn/GramMatrix_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. กำหนด Vector (State)
v1 = np.array([7, 1, 1, 1])
v2 = np.array([1, 8, 0.5, 0.5])
v3 = np.array([1.5, 1, 0.5, 7])

# รวมเป็น Matrix เดียว (ขนาด 3x4)
V = np.vstack([v1, v2, v3])

# 2. ทำ Normalization (ทำให้เป็น Unit Vector)
# np.linalg.norm(V, axis=1) หาความยาวของแต่ละ row
# keepdims=True เพื่อให้ shape ยังคงเป็น column vector สำหรับนำไปหารได้
norms = np.linalg.norm(V, axis=1, keepdims=True)
V_normalized = V / norms

print("Normalized Vectors:")
print(V_normalized)
print("-" * 20)

# 3. สร้าง Gram Matrix (G = V_norm dot V_norm.T)
# เพราะสมาชิก G_ij คือ dot product ของ row i และ row j
G_norm = np.dot(V_normalized, V_normalized.T)

print("Normalized Gram Matrix:")
print(G_norm)
print("-" * 20)

# 4. หา Determinant
det_val = np.linalg.det(G_norm)

print(f"Determinant: {det_val:.6f}")

Normalized Vectors:
[[0.97072534 0.13867505 0.13867505 0.13867505]
 [0.12356041 0.9884833  0.06178021 0.06178021]
 [0.20701967 0.13801311 0.06900656 0.96609178]]
--------------------
Normalized Gram Matrix:
[[1.         0.27415594 0.36364053]
 [0.27415594 1.         0.22595168]
 [0.36364053 0.22595168 1.        ]]
--------------------
Determinant: 0.786602
